easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Produit
#        - App\Entity\Category
#        - App\Entity\User
    site_name: 'gestion de mon site'
    user:
        display_name: true
        display_avatar: true
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"

